"""initial migration

Revision ID: d66767848efe
Revises: 
Create Date: 2026-02-08 09:55:53.162183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66767848efe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('meeting_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('meeting_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('has_blockers', sa.Boolean(), nullable=True),
    sa.Column('has_red_flags', sa.Boolean(), nullable=True),
    sa.Column('action_items_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_records_has_blockers'), 'meeting_records', ['has_blockers'], unique=False)
    op.create_index(op.f('ix_meeting_records_has_red_flags'), 'meeting_records', ['has_red_flags'], unique=False)
    op.create_index(op.f('ix_meeting_records_id'), 'meeting_records', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_records_meeting_type'), 'meeting_records', ['meeting_type'], unique=False)
    op.create_index(op.f('ix_meeting_records_status'), 'meeting_records', ['status'], unique=False)
    op.create_index(op.f('ix_meeting_records_user_id'), 'meeting_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_records_user_id'), table_name='meeting_records')
    op.drop_index(op.f('ix_meeting_records_status'), table_name='meeting_records')
    op.drop_index(op.f('ix_meeting_records_meeting_type'), table_name='meeting_records')
    op.drop_index(op.f('ix_meeting_records_id'), table_name='meeting_records')
    op.drop_index(op.f('ix_meeting_records_has_red_flags'), table_name='meeting_records')
    op.drop_index(op.f('ix_meeting_records_has_blockers'), table_name='meeting_records')
    op.drop_table('meeting_records')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
