import sys
import os
from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool
from alembic import context

# 1. Load environment variables from .env for local development
from dotenv import load_dotenv
load_dotenv()

# 2. Add your project root to sys.path so 'app' can be found
# This assumes env.py is in project_root/alembic/
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# 3. Import your models and metadata
# We import app.models to ensure all models are registered before autogenerate
import app.models 
from app.database import Base
target_metadata = Base.metadata

# This is the Alembic Config object
config = context.config

# 4. Helper function to get the URL dynamically from environment
def get_url():
    url = os.getenv("DATABASE_URL")
    if not url:
        # Fallback to the hardcoded URL in alembic.ini if .env is missing/not set
        return config.get_main_option("sqlalchemy.url")
    
    # FIX: Render and Supabase often provide 'postgres://' 
    # SQLAlchemy 1.4+ strictly requires 'postgresql://'
    if url.startswith("postgres://"):
        url = url.replace("postgres://", "postgresql://", 1)
    
    # FIX: Escape '%' for Alembic's ConfigParser 
    # (Supabase autogenerated passwords often have '%' which breaks the parser)
    return url.replace("%", "%%")

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    url = get_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()

def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    # Create a configuration dictionary that uses our dynamic URL
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = get_url()

    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection, 
            target_metadata=target_metadata
        )

        with context.begin_transaction():
            context.run_migrations()

if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()